USE ROLE ACCOUNTADMIN;

-- Create the database
CREATE DATABASE IF NOT EXISTS HOL_DB;

-- Create the schema inside the database
CREATE SCHEMA IF NOT EXISTS HOL_DB.HOL_SCHEMA;

CREATE TABLE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEWS (
  review_id STRING,
  product_type STRING,
  product_layout STRING,
  page_load_time FLOAT,
  product_rating INTEGER,
  product_review STRING,
  review_sentiment STRING,
  review_quality STRING
);

CREATE OR REPLACE NETWORK RULE INTERNET_ACCESS_RULE MODE = EGRESS TYPE = HOST_PORT VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80');
/* Create external access integration using the network rule */
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ALLOW_ALL_ACCESS_INTEGRATION ALLOWED_NETWORK_RULES = (INTERNET_ACCESS_RULE) ENABLED = true;

GRANT ALL PRIVILEGES ON INTEGRATION ALLOW_ALL_ACCESS_INTEGRATION 
    TO ROLE HOL_ROLE;

CREATE ROLE HOL_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;

GRANT ALL PRIVILEGES ON DATABASE HOL_DB TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA HOL_DB.HOL_SCHEMA TO ROLE HOL_ROLE;

CREATE COMPUTE POOL HOL_COMPUTE_POOL_HIGHMEM
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = HIGHMEM_X64_M;

GRANT USAGE ON COMPUTE POOL HOL_COMPUTE_POOL_HIGHMEM TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON TABLE TUBLAR_DATA TO ROLE HOL_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;

USE ROLE HOL_ROLE;

CREATE STAGE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEWS.REVIEW_STAGE;
  URL = 's3://sfquickstarts/vhol_building_ml_models_to_crack_the_code_of_customer_conversions/'
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"');

CREATE FILE FORMAT IF NOT EXISTS HOL_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

INSERT INTO HOL_DB.HOL_SCHEMA.REVIEWS (
    REVIEW_ID,
    PRODUCT_TYPE,
    PRODUCT_LAYOUT,
    PRODUCT_REVIEW,
    PAGE_LOAD_TIME,
    PRODUCT_RATING,
    REVIEW_SENTIMENT,
    REVIEW_QUALITY
)
SELECT
  t.$1,
  t.$2,
  t.$3,
  CASE
    WHEN t.$4 IS NULL OR TRIM(t.$4) = '' THEN 'TBD'
    ELSE t.$4
  END,
  t.$5::FLOAT,
  t.$6::INT,
  'unknown',
  'pending'
FROM @REVIEW_STAGE (FILE_FORMAT => HOL_CSV_FORMAT) t
WHERE METADATA$FILENAME ILIKE 'review_table_export_%.csv';