USE ROLE ACCOUNTADMIN;

-- Create the database
CREATE DATABASE IF NOT EXISTS HOL_DB;

-- Create the schema inside the database
CREATE SCHEMA IF NOT EXISTS HOL_DB.HOL_SCHEMA;

CREATE WAREHOUSE IF NOT EXISTS HOL_WAREHOUSE
  WAREHOUSE_SIZE = MEDIUM
  WAREHOUSE_TYPE = STANDARD
  RESOURCE_CONSTRAINT = STANDARD_GEN_2;

CREATE TABLE IF NOT EXISTS HOL_DB.HOL_SCHEMA.TABULAR_DATA (
  UUID STRING,
  PRODUCT_TYPE STRING,
  PRODUCT_LAYOUT STRING,
  PAGE_LOAD_TIME FLOAT,
  PRODUCT_RATING INT,
  PURCHASE_DECISION INT
);

CREATE TABLE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEWS (
  UUID STRING,
  REVIEW_TEXT STRING,
  REVIEW_QUALITY STRING,
  REVIEW_SENTIMENT FLOAT
);

CREATE OR REPLACE NETWORK RULE INTERNET_ACCESS_RULE MODE = EGRESS TYPE = HOST_PORT VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80');
/* Create external access integration using the network rule */
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ALLOW_ALL_ACCESS_INTEGRATION ALLOWED_NETWORK_RULES = (INTERNET_ACCESS_RULE) ENABLED = true;

GRANT ALL PRIVILEGES ON INTEGRATION ALLOW_ALL_ACCESS_INTEGRATION 
    TO ROLE HOL_ROLE;

CREATE ROLE HOL_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON DATABASE HOL_DB TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA HOL_DB.HOL_SCHEMA TO ROLE HOL_ROLE;

CREATE COMPUTE POOL HOL_COMPUTE_POOL_HIGHMEM
  MIN_NODES = 1
  MAX_NODES = 3
  INSTANCE_FAMILY = HIGHMEM_X64_M;

GRANT USAGE ON COMPUTE POOL HOL_COMPUTE_POOL_HIGHMEM TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON TABLE TUBLAR_DATA TO ROLE HOL_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;

USE ROLE HOL_ROLE;

CREATE STAGE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEWS.REVIEW_STAGE
  URL = 's3://sfquickstarts/vhol_building_ml_models_to_crack_the_code_of_customer_conversions/csv/'
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"');

CREATE STAGE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEWS.REVIEWS
  URL = 's3://sfquickstarts/vhol_building_ml_models_to_crack_the_code_of_customer_conversions/txt/'
  DIRECTORY = (ENABLE = TRUE);

CREATE FILE FORMAT IF NOT EXISTS HOL_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

INSERT INTO HOL_DB.HOL_SCHEMA.TABULAR_DATA (
    UUID,
    PRODUCT_TYPE,
    PRODUCT_LAYOUT,
    PAGE_LOAD_TIME,
    PRODUCT_RATING
)
SELECT
  t.$1,
  t.$2,
  t.$3,
  t.$5::FLOAT,
  t.$6::INT
FROM @REVIEW_STAGE (FILE_FORMAT => HOL_CSV_FORMAT) t
WHERE METADATA$FILENAME ILIKE 'review_table_export_%.csv';

INSERT INTO HOL_DB.HOL_SCHEMA.REVIEWS (
    UUID,
    REVIEW_TEXT
)
SELECT
  t.$1,
  CASE
    WHEN t.$4 IS NULL OR TRIM(t.$4) = '' THEN 'TBD'
    ELSE t.$4
  END
FROM @REVIEW_STAGE (FILE_FORMAT => HOL_CSV_FORMAT) t
WHERE METADATA$FILENAME ILIKE 'review_table_export_%.csv';