USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS HOL_WAREHOUSE
  WAREHOUSE_SIZE = MEDIUM
  WAREHOUSE_TYPE = STANDARD
  RESOURCE_CONSTRAINT = STANDARD_GEN_2;

-- Create the database
CREATE DATABASE IF NOT EXISTS HOL_DB;

-- Create the schema inside the database
CREATE SCHEMA IF NOT EXISTS HOL_DB.HOL_SCHEMA;

USE DATABASE HOL_DB;
USE SCHEMA HOL_DB.HOL_SCHEMA;

-- Create the tables inside the schema
CREATE TABLE IF NOT EXISTS HOL_DB.HOL_SCHEMA.TABULAR_DATA (
  UUID STRING,
  PRODUCT_TYPE STRING,
  PRODUCT_LAYOUT STRING,
  PAGE_LOAD_TIME FLOAT,
  PRODUCT_RATING INT,
  PURCHASE_DECISION INT
);

-- Create the table for reviews
CREATE TABLE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEWS (
  UUID STRING,
  REVIEW_TEXT STRING,
  REVIEW_QUALITY STRING,
  REVIEW_SENTIMENT FLOAT
);

CREATE OR REPLACE NETWORK RULE INTERNET_ACCESS_RULE MODE = EGRESS TYPE = HOST_PORT VALUE_LIST = ('0.0.0.0:443', '0.0.0.0:80');
/* Create external access integration using the network rule */
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION ALLOW_ALL_ACCESS_INTEGRATION ALLOWED_NETWORK_RULES = (INTERNET_ACCESS_RULE) ENABLED = true;

CREATE ROLE IF NOT EXISTS HOL_ROLE;
GRANT USAGE ON INTEGRATION ALLOW_ALL_ACCESS_INTEGRATION TO ROLE HOL_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON DATABASE HOL_DB TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA HOL_DB.HOL_SCHEMA TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON TABLE TABULAR_DATA TO ROLE HOL_ROLE;
GRANT ALL PRIVILEGES ON TABLE REVIEWS TO ROLE HOL_ROLE;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE HOL_ROLE;
GRANT USAGE ON WAREHOUSE HOL_WAREHOUSE TO ROLE HOL_ROLE;

EXECUTE IMMEDIATE $$
DECLARE 
    stmt STRING;
BEGIN
    stmt := CONCAT('GRANT ROLE HOL_ROLE TO USER ', CURRENT_USER(), ';');
    EXECUTE IMMEDIATE stmt;
END;
$$;

USE ROLE HOL_ROLE;

CREATE STAGE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEW_STAGE
  URL = 's3://sfquickstarts/vhol_building_ml_models_to_crack_the_code_of_customer_conversions/csv/'
  DIRECTORY = (ENABLE = TRUE)
  FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY = '"');

CREATE STAGE IF NOT EXISTS HOL_DB.HOL_SCHEMA.EXTERNAL_REVIEWS
  URL = 's3://sfquickstarts/vhol_building_ml_models_to_crack_the_code_of_customer_conversions/txt/'
  DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS HOL_DB.HOL_SCHEMA.REVIEWS
    DIRECTORY = (ENABLE = TRUE);

COPY FILES
  INTO @REVIEWS
  FROM @EXTERNAL_REVIEWS;

CREATE FILE FORMAT IF NOT EXISTS HOL_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

INSERT INTO HOL_DB.HOL_SCHEMA.TABULAR_DATA (
    UUID,
    PRODUCT_TYPE,
    PRODUCT_LAYOUT,
    PAGE_LOAD_TIME,
    PRODUCT_RATING,
    PURCHASE_DECISION
)
SELECT
  t.$1,
  t.$2,
  t.$3,
  t.$4::FLOAT,
  t.$5::INT,
  t.$6::INT
FROM @REVIEW_STAGE/tabular_data.csv (FILE_FORMAT => HOL_CSV_FORMAT) t;

INSERT INTO HOL_DB.HOL_SCHEMA.REVIEWS (
    UUID,
    REVIEW_TEXT,
    REVIEW_QUALITY
)
SELECT
  t.$1,
  t.$2,
  t.$3
FROM @REVIEW_STAGE (FILE_FORMAT => HOL_CSV_FORMAT) t
WHERE REGEXP_LIKE(METADATA$FILENAME, '.*review_table__.*\\.csv$');

USE ROLE ACCOUNTADMIN;

CREATE COMPUTE POOL IF NOT EXISTS HOL_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 4
  INSTANCE_FAMILY = CPU_X64_M;

GRANT USAGE ON COMPUTE POOL HOL_COMPUTE_POOL TO ROLE HOL_ROLE;